# Lab1 : Skalar, Vektor, Matriks, dan Tensor 

Notebook ini merupakan suplemen dari kegiatan laboratorium di Bab 1: Aljabar Linier.

Pada kegiatan laboratorium ini, kita akan mencoba menerapkan dasar - dasar operasi di dalam Aljabar Linier dengan menggunakan pustaka komputasi numerik NumPy untuk memanipulasi *array* di lingkungan Python.

### 1. Memulai sesi NumPy
Guna memastikan kita telah melakukan pengaturan lingkungan komputasi yang sesuai, kita dapat menjalankan perintah berikut ini:

In [2]:
import sys
import numpy as np

print("Python: {}".format(sys.version))
print("NumPy: {}".format(np.__version__))

Python: 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0]
NumPy: 1.18.1


Kita dapat mendefinisikan skalar (yang mana merupakan nilai bilangan tunggal) dengan menggunakan operator `=` untuk penugasan ke suatu variabel tertentu.

In [2]:
# penugasan skalar
x = 128
x

128

Dengan NumPy, kita dapat mendefinisikan vektor dengan menggunakan fungsi `array()`

In [3]:
# penugasan vektor
x = np.array((1,2,8))
x

array([1, 2, 8])

*Array* mempunyai beberapa atribut yang dapat memberitahu kita tentang informasi terkait dimensi dan ukuran suatu vektor:

In [4]:
print("Dimensi vektor: {}".format(x.shape))
print("Ukuran vektor: {}".format(x.size))

Dimensi vektor: (3,)
Ukuran vektor: 3


Untuk mendefinisikan matriks, kita dapat menggunakan fungsi `matrix()` di pustaka NumPy. Guna memisahkan baris antar matriksnya, kita dapat menggunakan tanda `[]` dan koma.

In [5]:
X = np.matrix([[1,2,8],[2,2,0],[3,2,0]])
X

matrix([[1, 2, 8],
        [2, 2, 0],
        [3, 2, 0]])

In [6]:
print('Dimensi matriks: {}'.format(X.shape))
print('Ukuran matriks: {}'.format(X.size))

Dimensi matriks: (3, 3)
Ukuran matriks: 9


NumPy memudahkan kita untuk mendefinisikan matriks secara cepat, misalkan pada kasus ini kita hendak mendefinisikan matriks identitas $3 \times 3$, kita tinggal menggunakan fungsi `ones()`:

In [7]:
X = np.ones((3,3))
X

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
print('Dimensi matriks: {}'.format(X.shape))
print('Ukuran matriks: {}'.format(X.size))

Dimensi matriks: (3, 3)
Ukuran matriks: 9


Sebagai manusia yang hidup di ruang tiga dimensi, tentu kita akan sangat kesulitan ketika memvisualisasikan tensor berdimensi banyak, namun NumPy mempermudah kita untuk melakukan pendefinisian ini dengan menggunakan satu baris perintah:

In [9]:
X = np.ones((3,3,3))
X

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
print("Dimensi tensor: {}".format(x.shape))
print("Ukuran tensor: {}".format(x.size))

Dimensi tensor: (3,)
Ukuran tensor: 3


### 2. Pengindeksan

Bagian ini mencoba untuk memfamiliarkan konvensi pengindeksan NumPy.

In [11]:
A = np.ones((5,5), dtype = np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
# pengindeksan dimulai dari 0
A[0,1] = 2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
# Penting untuk dicatat jika NumPy melakukan pengindeksan dengan konvensi baris, kolom 
# Kita dapat melakukan penugasan seluruh baris atau kolom dengan menggunakan operator : 
A[:,0] = 3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [14]:
# Hal ini berlaku juga untuk Tensor berdimensi banyak 
A = np.ones((5,5,5), dtype = np.int)

# Berikut ini contohnya
A[:,0,0] = 128
print(A)

[[[128   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]]

 [[128   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]]

 [[128   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]]

 [[128   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]]

 [[128   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]]]


### 3. Operasi - Operasi Matriks

Bagian ini merupakan demo operasi penjumlahan, pengurangan, dan perkalian matriks

In [15]:
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)

In [16]:
print(A)

[[1 2]
 [3 4]]


In [17]:
print(B)

[[1 1]
 [1 1]]


In [18]:
# Penjumlahan antar elemen
C = A + B
print(C)

[[2 3]
 [4 5]]


In [19]:
# Pengurangan antar elemen
C = A - B
print(C)

[[0 1]
 [2 3]]


In [20]:
# Perkalian matriks
C = A*B
print(C)

[[3 3]
 [7 7]]


### 4. Transpos matriks

Transpos digunakan untuk menukar elemen antar baris dan kolom pada suatu *array*. NumPy memudahkan kita untuk melakukan operasi transpos matriks secara efisien.

In [21]:
A = np.array(range(9))
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
# operasi transpos
B = A.T
print(B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [23]:
# dengan melakukan double-transpose, maka kita akan mendapatkan matriks awal
C = B.T
print(C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# Tranpos dapat dilakukan pada matriks dengan ukuran berbeda
A = np.arange(10)
A = A.reshape(2,5)
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 5. Tensor berdimensi banyak

Seperti yang telah dijabarkan sebelumnya, NumPy mempermudah kita untuk melakukan pengolahan data pada tensor berdimensi raksasa. Berikut ini salah satu contoh pendefinisian *array* berdimensi 10.

In [4]:
A = np.ones((3,3,3,3,3,3,3,3,3,3))

In [26]:
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
